### ISSUE TITLE
ssdb不支持python3吗？

### ISSUE THREAD

**Issue by xcf007** [wrongwaycn/ssdb-py#8]

**Comment by xcf007** [comment]
python2安装成功，python3的pip下安装失败

=============================================
Collecting ssdb
  Using cached ssdb-0.0.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "D:\*****\Temp\pip-build-39owu3zw\ssdb\setup.py", line 5, in <modu
le>
        from ssdb import __version__
      File "D:\******\Temp\pip-build-39owu3zw\ssdb\ssdb\__init__.py", line 2,
in <module>
        from ssdb.client import StrictSSDB, SSDB
      File "D:\**************\Temp\pip-build-39owu3zw\ssdb\ssdb\client.py", line 3, in
 <module>
        from itertools import chain, starmap, izip_longest
    ImportError: cannot import name 'izip_longest'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in D:\************\Temp\
pip-build-39owu3zw\ssdb\

**Comment by jhao104** [comment]
我也遇到这个问题，izip_longest在py3里面叫zip_longest
```
try:
    # Python 3
    from itertools import zip_longest as izip_longest 
except ImportError:
    # Python 2
    from itertools import izip_longest
# use the name zip_longest
```

**Comment by vmvz** [comment]
@jhao104  就这一个问题吗? 我还准备用python3 了

**Comment by jhao104** [comment]
@vmvz 我是已经不用ssdb.py了。 用redis.py连接ssdb

**Comment by vmvz** [comment]
@jhao104 还可以用 redis.py 连 ssdb?

https://github.com/andymccurdy/redis-py

直接用? 需要修改什么吗?

**Comment by jhao104** [comment]
@vmvz 连接方式一样的，ssdb和redis协议一样的。
只是命令不一样的，redis.py不支持的命令可以使用 `execute_command`方法。具体的你可以参考这个:
https://github.com/jhao104/SSDBAdmin/blob/88122310ca27725c2afaee978809ecdaff59a204/SSDBAdmin/model/ssdb_admin.py#L56

**Comment by vmvz** [comment]
@jhao104 非常感谢, 我也现在用redis.py, 然后自己封装一下.

原来一直用 https://github.com/wrongwaycn/ssdb-py , 这个作者一直没有更新过了

**Comment by vmvz** [comment]
@jhao104 用了一段时间, 发现 redis.py 没有这个好用呀. 我尝试把这个修复一下,升级维护.

这份代码还是很好的
